server:
  port: 8090
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
      client:
        registration:
          resource-server:
           provider: spring
           client-id: resource-server
           client-secret: resource-server
           authorization-grant-type: client_credentials
           scope: 
            - articles.read
           client-name: resource-server
        provider:
          spring:
           issuer-uri: http://auth-server:9000
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: Htht123.com
# security:
#     oauth2:
#       client:
#         registration:
# gateway-scope:
#             provider: spring
#             client-id: gateway
#             client-secret: gatewaysecret
#             authorization-grant-type: client_credentials
#             redirect-uri: "http://127.0.0.1:10000/login/oauth2/code/{registrationId}"
#             scope: 
#              - articles.read
#             client-name: gateway
